const mongoose = require('mongoose')
const Schema = mongoose.Schema



const surveySchema = new Schema({
  name: { type: String, required: true },
  civilStatus: { type: String, required: true },
  sex: { type: String, required: true },
  age: { type: Number, required: true },
  hhMember: { type: String, required: true },
  fishR: { type: String, required: true },
  boatR: { type: String, required: true },
  nameAssoc: { type: String, required: true },
  totalMember: { type: Number, required: true },
  province: { type: String, required: true },
  municipality: { type: String, required: true },
  baranggay: { type: String, required: true },
  projectReceived: { type: String, required: true },
  specProject: { type: String, required: true },
  noUnitsReceived: { type: Number, required: true },
  dateReceived: { type: Date, required: true },
  mainIncome: { type: String, required: true },
//   otherIncome: { type: String, required: true },




  quantity: { type: String, required: true },
  quantityReason: { type: String },
  quantityRating: { type: Number, min: 1, max: 5, required: true },
  quality: { type: String, required: true },
  qualityReason: { type: String },
  qualityRating: { type: Number, min: 1, max: 5, required: true },
  q2: { type: String, required: true },
  q2Reason: { type: String },
  timelinessRating: { type: Number, min: 1, max: 5, required: true },
  uponRequest: { type: String, required: true },
  q3: { type: String, required: true },
  q3Reason: { type: String },
  challenges: { type: String, required: true },
  relevanceRating: { type: Number, min: 1, max: 5, required: true },
  q4: { type: String, required: true },
  q4Reason: { type: String },
  q5: { type: String, required: true },
  q5Reason: { type: String },
  coherenceRating: { type: Number, min: 1, max: 5, required: true },
  q6: { type: String, required: true },
  q6Reason: { type: String },
  q7Satisfied: { type: String, required: true },
  q7_1: { type: String},
  q7_1Reason: { type: String },
  satisfactionRating: { type: Number, min: 1, max: 5, required: true },
  q7_2: { type: String, required: true },
  q7_2Reason: { type: String },
  q8: { type: String, required: true },
  q8Reason: { type: String },
  q9_1: { type: String, required: true },
  q9_1Spec: { type: String },
  q9_2: { type: String, required: true },
  q9_3: { type: String, required: true },
  q9_4: { type: String, required: true },
  q9_5: { type: String, required: true },
  q9_6: { type: String, required: true },
  q9_7: { type: String, required: true },
  q9_8: { type: String, required: true },
  q9_9: { type: String, required: true },
  q9_10: { type: String, required: true },
  q10_e: { type: String },
  q9_11: { type: String, required: true },
  q9_11other: { type: String },
  q9_12: { type: String, required: true },
  q9_12Spec: { type: String },
  q9_13: { type: String},
  q9_13other: { type: String },
  q9_14: { type: String},
  impactRating: { type: Number, min: 1, max: 5, required: true },
  q10: { type: String, required: true },
  q10Reason: { type: String },
  q10_1: { type: String, required: true },
  sustainabilityRating: { type: Number, min: 1, max: 5, required: true },
  q11: { type: String, required: true },
  q11_1: { type: String, required: true },
  q12: { type: String, required: true },
  note: { type: String, required: true }
},
{ timestamps: true });

const Survey = mongoose.model('Survey', surveySchema);

module.exports = Survey;
